import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { SpecArtifact } from '../types/spec.types';

export async function generateZip(
  artifacts: SpecArtifact[],
  moduleName: string
): Promise<Blob> {
  const zip = new JSZip();

  // Create folder structure
  const moduleFolder = zip.folder(`specs/${moduleName}`);

  if (!moduleFolder) {
    throw new Error('Failed to create module folder in ZIP');
  }

  // Add artifacts to ZIP
  for (const artifact of artifacts) {
    const filePath = artifact.filePath;

    // Handle nested paths (e.g., interfaces/user-repository.spec)
    if (filePath.includes('/')) {
      const parts = filePath.split('/');
      const fileName = parts.pop()!;
      const folderPath = parts.join('/');

      const folder = moduleFolder.folder(folderPath);
      if (folder) {
        folder.file(fileName, artifact.content);
      }
    } else {
      moduleFolder.file(filePath, artifact.content);
    }
  }

  // Add a README
  const readme = generateReadme(moduleName, artifacts);
  moduleFolder.file('README.md', readme);

  // Generate ZIP blob
  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return blob;
}

export function downloadZip(blob: Blob, moduleName: string): void {
  const timestamp = new Date().toISOString().split('T')[0];
  const fileName = `${moduleName}-specs-${timestamp}.zip`;
  saveAs(blob, fileName);
}

function generateReadme(moduleName: string, artifacts: SpecArtifact[]): string {
  const lines: string[] = [
    `# ${moduleName} Spec IR Artifacts`,
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Contents',
    '',
  ];

  // Group artifacts by type
  const byAgent = new Map<string, SpecArtifact[]>();
  for (const artifact of artifacts) {
    const agent = artifact.createdBy;
    if (!byAgent.has(agent)) {
      byAgent.set(agent, []);
    }
    byAgent.get(agent)!.push(artifact);
  }

  // List artifacts by agent
  const agentOrder = ['product', 'architect', 'scrum', 'developer', 'tester', 'devops'];

  for (const agent of agentOrder) {
    const agentArtifacts = byAgent.get(agent);
    if (agentArtifacts && agentArtifacts.length > 0) {
      lines.push(`### ${agent.charAt(0).toUpperCase() + agent.slice(1)} Agent`);
      for (const artifact of agentArtifacts) {
        lines.push(`- \`${artifact.filePath}\``);
      }
      lines.push('');
    }
  }

  lines.push('## Usage');
  lines.push('');
  lines.push('These Spec IR files can be consumed by external language agents to generate:');
  lines.push('- Source code in your target language (Java, Go, TypeScript, etc.)');
  lines.push('- Infrastructure as Code (Terraform, Pulumi)');
  lines.push('- Database migrations');
  lines.push('- Test implementations');
  lines.push('- CI/CD configurations');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('Generated by Spec - A Language-Agnostic IR for Autonomous Software Development');

  return lines.join('\n');
}
